### ISSUE TITLE
Anlegen einer Internship -> Server Error

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#164]
Create New Internship -> speichern ohne Werte eingegeben zu haben ->
 app/controllers/internships_controller.rb:105:in `show'

ActionView::Template::Error: undefined method `-' for nil:NilClass
	from /Users/kleinen/mine/current/htw/imi-maps/code/imimaps/app/models/internship.rb:64:in `weekCount'
	from /Users/kleinen/mine/current/htw/imi-maps/code/imimaps/app/views/internships/show.html.erb:170:in `_app_views_internships_show_html_erb__749611626704085601_70218648480920'
	from /Users/kleinen/.rvm/gems/ruby-2.4.1@imi-maps-rails42-bootstrap-update/gems/actionview-4.2.9/lib/action_view/template.rb:145:in `block in render'

**Comment by bkleinen** [comment]
obsolete.
